name: Bug Bounty PR Labeling

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  check_issue_and_add_bugbounty:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
    - name: Check for 'bugbounty' label on related issue
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const issueNumber = context.payload.pull_request.body.match(/#(\d+)/);
          if (!issueNumber) return;
          const issue = await github.rest.issues.get({
            owner: 'DevlUp-Labs',
            repo: 'dev-playground',
            issue_number: issueNumber[1],
          });
          if (issue.data.labels.some(label => label.name === 'bugbounty')) {
            await github.rest.issues.addLabels({
              owner: 'DevlUp-Labs',
              repo: 'dev-playground',
              issue_number: context.payload.pull_request.number,
              labels: ['bugbounty'],
            });
          }

  add_bugbountyverified_on_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Add 'bugbountyverified' label on PR merge
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.rest.issues.addLabels({
            owner: 'DevlUp-Labs',
            repo: 'dev-playground',
            issue_number: context.payload.pull_request.number,
            labels: ['bugbountyverified'],
          });
